apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  gateways:
    - istio-ingress/istio-ingressgateway
    - keycloak/keycloak
  hosts:
    - keycloak.arielsofi.com
    - keycloak.keycloak.svc.cluster.local
    - keycloak.keycloak
    - keycloak.keycloak.svc
  http:
    - route:
        - destination:
            host: keycloak.keycloak.svc.cluster.local
            port:
              number: 80
