cert-manager:
  clusterResourceNamespace: istio-system
  featureGates: "ExperimentalCertificateSigningRequestControllers=true"
  global:
    leaderElection:
      namespace: istio-system
  installCRDs: true
  namespace: istio-system
  # tolerations:
  # - key: "node_type"
  #   operator: "Equal"
  #   value: "system"
  #   effect: "NoSchedule"