apiVersion: v2
name: oauth2-proxy
description: A Helm chart for oauth2-proxy
type: application

version: 0.0.1
appVersion: 7.3.0

dependencies:
  - name: oauth2-proxy
    version: 6.2.7
    repository: https://oauth2-proxy.github.io/manifests